### ISSUE TITLE
Update SAL_USE_VCLPLUGIN in startlxqt so that users can open files easily in Libreoffice

### ISSUE THREAD

**Issue by yan12125** [lxqt/lxqt#1673]
##### Expected Behavior
When using LXQt, opening files in libreoffice is as easy as other programs

##### Current Behavior
With Libreoffice 6.2.0, hitting Ctrl + O makes libreoffice hang if kio is not installed.

##### Possible Solution
Update the default SAL_USE_VCLPLUGIN in startlxqt (details below)

##### Steps to Reproduce (for bugs)
1. Upgrade to the latest Arch Linux
2. Install community/libreoffice-fresh 6.2.0-3
3. Make sure kio is not installed
4. Ctrl + O

##### Context
I'm an occasional Libreoffice user

##### System Information
* Distribution & Version: Arch Linux up-to-date
* Kernel: 4.20.8-arch1-1-ARCH
* Qt Version: 5.12.1-2
* liblxqt Version: 0.14.0.2.gbad0c78-1
* Package version: all git-master

---

With the latest Libreoffice, there are at least 3 possible values for the SAL_USE_VCLPLUGIN environment variable:

* Run `SAL_USE_VCLPLUGIN=qt5 libreoffice` from the terminal: Ctrl + O runs a Qt-style file dialog (native Qt file dialog?)

![default](https://user-images.githubusercontent.com/1937689/52788394-be2a0600-309b-11e9-884b-f24acf6f4e40.png)

* `SAL_USE_VCLPLUGIN=kde5 libreoffice`: There are two possible results after hitting Ctrl + O:

-> if `kio` is NOT installed: 
```
/usr/lib/libreoffice/program/lo_kde5filepicker: error while loading shared libraries: libKF5KIOFileWidgets.so.5: cannot open shared object file: No such file or directory
```
And then libreoffice hangs.

-> if `kio` is installed: 

![default](https://user-images.githubusercontent.com/1937689/52788520-2bd63200-309c-11e9-8c7d-729c64166561.png)

* `SAL_USE_VCLPLUGIN=gtk3 libreoffice`: GTK+ file dialog is used

---

Currently, startlxqt declared SAL_USE_VCLPLUGIN=kde4. As this is no longer a valid option, libreoffice fallbacks to kde5, and thus hangs at Ctrl + O if kio is not installed.

IMO startlxqt should be updated to use another value for SAL_USE_VCLPLUGIN. Looks like `qt5` is a safe value. Testing on other distros will also be constructive, of course.

**Comment by palinek** [comment]
Seems you spend quite a time with this... and I agree with your conclusion.

**Comment by yan12125** [comment]
Well, this is more a "call for tests" and a note for conclusions.

TODO:
* Check if SAL_USE_VCLPLUGIN=qt5 breaks older libreoffice or not?
* Complain to the libreoffice team for the strange default (kde5)
* Looks like qtpluging is not loaded when VCLPLUGIN=qt5 is used. Investigate that.

**Comment by tsujan** [comment]
Hadn't used LibreOffice for a while. It became GTK+ oriented, which was good, IMO, because such problems were gone: an app with an acceptable GTK+ look and feel that worked fine. V6 brought back the poor Qt skin support. Its poorness may not be apparent with Fusion or Breeze...

**Comment by yan12125** [comment]
Oh, that reminds me - with `SAL_USE_VCLPLUGIN=qt5`, toolbar icons in Libreoffice Calc appear blurry.

Before the new Qt skin is as good is the GTK+ one, using SAL_USE_VCLPLUGIN=gtk3 might be better. Actually that's what I'm using now.

@tsujan Do you mind sharing some screenshots in before flames about "why not using the new Qt skin"?

**Comment by yan12125** [comment]
A screenshot of Libreoffice Calc Toolbar under Fusion - 
![default](https://user-images.githubusercontent.com/1937689/53095511-03e14580-3558-11e9-840d-0b65210dd3c6.png)

**Comment by tsujan** [comment]
QStyle supports many valid combinations that can't be found in Breeze/Fusion and I don't expect LibreOffice's Qt5 skin to "understand" them but, when developers come to Qt, they usually make weird mistakes.

For example, it's completely valid for a light Qt style to have dark toolbars, menubars and menus:

![kvantum](https://user-images.githubusercontent.com/981076/53096174-c5d22a80-3533-11e9-9b4d-bbadcd6d412a.png)

But LibreOffice can't support it:

![libreoffice](https://user-images.githubusercontent.com/981076/53096188-ccf93880-3533-11e9-82cf-6d15ce3cc402.png)

I might try to add worarunds for such cases in Kvantum but, frankly, I've got tired of adding workarounds for others' messes.

Fortunately, it's possible to assign a separate theme to LibreOffice with Kvantum, so that the above-mentioned mess isn't important. In short, I'm not against using of the Qt skin.

**Comment by tsujan** [comment]
A simple Kvantum theme that's supported by LibreOffice:

![kvantum1](https://user-images.githubusercontent.com/981076/53096899-71c84580-3535-11e9-965a-6476cdb02974.png)

So, there's no disaster.

**Comment by yan12125** [comment]
I guess the remaining issue is unrelated to Kvantum, but can you get the enhanced open file dialog (https://github.com/lxqt/lxqt-qtplugin/pull/23) working?

**Comment by tsujan** [comment]
> can you get the enhanced open file dialog

Yes, because I also have a KDE installation and so, kio.

I can't uninstall kio but if LibreOffice hangs without it, it's an important bug that should be reported to its developers.

**Comment by tsujan** [comment]
Found the needed workarounds for the new LibreOffice's Qt5 skin; will add them to Kvantum soon:

![kvantum2](https://user-images.githubusercontent.com/981076/53103300-9a0a7100-3542-11e9-883a-eb9db71392c2.png)

So far, so good. Apart from the kio issue and although not elegant, the Qt5 skin is more or less usable with all Qt themes.

**Comment by yan12125** [comment]
> Complain to the libreoffice team for the strange default (kde5)

OK, here you go: https://bugs.documentfoundation.org/show_bug.cgi?id=123595

**Comment by tsujan** [comment]
> OK, here you go: https://bugs.documentfoundation.org/show_bug.cgi?id=123595

"Actual Results:" and "Expected Results:" are reversed ;) However, I'm sure they'll understand the problem.

The problem isn't specific to LXQt: any Qt DE other than KDE that has a file dialog may reveal it but I think there is none other than LXQt -- or at least, LXQt is the most well-known.

**Comment by yan12125** [comment]
Oops, I'm too tired to write a proper bug report :P

And thanks for efforts on Kvantum! Hopefully they will know how incomplete their Qt backend is :/

**Comment by tsujan** [comment]
> Hopefully they will know how incomplete their Qt backend is

I think this is the most that can be done. It's a little better than the Qt4 skin.

**Comment by tsujan** [comment]
After inspecting the new Qt skin, I should admit that I'd badly underestimated it. Actually, it's much better than old skins -- even better than the GTK skin. LibreOffice devs have done a great job here, supporting `QStyle` in places that surprised me:

![writer](https://user-images.githubusercontent.com/981076/53128936-597b1980-357b-11e9-902e-9e152a5d0a57.png)

My mistake was that I'd limited my expectations to what I'd seen in the old Qt4 skin.

**Comment by tsujan** [comment]
@yan12125, this may be interesting to you:

I wanted to test Plasma wayland after a KDE update. So I logged out of LXQt and logged into Plasma wayland. While I was impressed by improvements in KDE's wayland support, I remembered this issue and launched Writer. To my surprise, it was styled by Breeze, while my active widget style is Kvantum under KDE (all other Qt apps use Kvantum).

It's good that LibreOffice is styled by the active Qt style under LXQt (contrary to KDE). There should be some KDE setting -- or EV -- that, fortunately, doesn't work under LXQt. I didn't looked into it further.

**Comment by yan12125** [comment]
Whoa, so more bugs either in KDE or in libreoffice? TODO list grows lol

Right now I'm stucked with linking issues of the KDE VCL plugin in libreoffice. Not able to check how it goes on under KDE or Wayland, by the way.

**Comment by stefonarch** [comment]
Just stumpled on [this bug](https://forum.manjaro.org/t/erasing-of-text-not-working-in-libreoffice-calc-6-2-0-3/76238) in libreoffice: backspace in calc is not working anymore, workaround is `export SAL_USE_VCLPLUGIN=gtk3; libreoffice --calc`

**Comment by tsujan** [comment]
@stefonarch With the Qt5 skin, pasting inside the search box of Writer as well as inside its text view has serious problems. I didn't know that until I really started to use Writer.

**Comment by yan12125** [comment]
Thank you both for testing! Sounds like it's better to stick with the GTK+3 backend in LXQt. By the way, I haven't had time to investigate linking issues in the KDE VCL plugin, either.

**Comment by tsujan** [comment]
> Sounds like it's better to stick with the GTK+3 backend in LXQt.

Yes, for now, because Qt5 skin sacrifices usability for a uniform look and feel and that's bad.

**Comment by slacka** [comment]
This issue was fixed upstream and backported to 6.2

https://bugs.documentfoundation.org/show_bug.cgi?id=122752

**Comment by yan12125** [comment]
Thanks for the link. I know that issue, and I've tried to build 6.2 rc on Arch Linux. The issue is still there in 6.2 rc. I'm not sure if I've built libreoffice correctly or not, though.

**Comment by yan12125** [comment]
In https://bugs.documentfoundation.org/show_bug.cgi?id=123595#c5, an LibreOffice dev mentions the Qt5 VCL plugin combined with an extra environment variable SAL_VCL_QT5_USE_CAIRO=true is an alternative. On my machine the appearance is quite different.

**Comment by tsujan** [comment]
@yan12125 

Facts until now:

(1) The new Qt5 skin draws some parts of LibreOffice like Qt5 apps. That's very good.
(2) It draws some other parts of LibreOffice inconsistently. That's tolerable.
(3) It interferes with text pasting (and maybe, with some other important jobs). That's very bad.

IMO, (3) makes the Qt5 skin unusable. Until (3) is fixed, I won't -- actually, I couldn't -- use the Qt5 skin :(

**Comment by michaelweghorn** [comment]
> @yan12125
> [...]
> (3) It interferes with text pasting (and maybe, with some other important jobs). That's very bad.
> 
> IMO, (3) makes the Qt5 skin unusable. Until (3) is fixed, I won't -- actually, I couldn't -- use the Qt5 skin :(

FYI, (3) sounds like the issue described and fixed in upstream bug https://bugs.documentfoundation.org/show_bug.cgi?id=122689

In any way, there's certainly still a bunch of bugs in the new qt5 and kde5 VCL plugins, s. in particular the upstream meta bug https://bugs.documentfoundation.org/show_bug.cgi?id=102495 for known issues. Most of the bugs have their root cause inside the qt5 VCL plugin, which is the base for the kde5 one, so if you prefer robustness over tighter desktop integration, gtk3 is probably a "safer" choice as of now...

**Comment by michaelweghorn** [comment]
> Just stumpled on [this bug](https://forum.manjaro.org/t/erasing-of-text-not-working-in-libreoffice-calc-6-2-0-3/76238) in libreoffice: backspace in calc is not working anymore, workaround is `export SAL_USE_VCLPLUGIN=gtk3; libreoffice --calc`

And that sounds like https://bugs.documentfoundation.org/show_bug.cgi?id=122238 - also fixed in the meanwhile. :-)

**Comment by tsujan** [comment]
> FYI, (3) sounds like the issue described and fixed in upstream bug 

@michaelweghorn, thanks! (3) was the worst bug I encountered; its being fixed was good news.

A big Manjaro update came tonight; will do it, shut down the laptop and check LibreOffice-fresh tomorrow.

**Comment by tsujan** [comment]
And kudos to LibreOffice devs! Making a Qt skin like this was a hard job.

**Comment by yan12125** [comment]
From the linked LibreOffice issue:
```
For reference, at a quick glance the current handling of LXQt was introduced by
this commit:

commit ac9c14dbbd3a4341de0aa1b1dbc37ad2ce69398c
Author: Simon Quigley <tsimonq2@ubuntu.com>
Date:   Wed Oct 10 21:16:17 2018 -0500

    Add support for LXQt as a Linux desktop environment.

    This change makes LXQt use the Breeze icon theme, and adds it as a
    desktop environment along the other supported DEs.
```

The relevant commit is https://cgit.freedesktop.org/libreoffice/core/commit/?id=ac9c14dbbd3a4341de0aa1b1dbc37ad2ce69398c.

@tsimonq2 "makes LXQt use the Breeze icon theme" is good, while broken file dialogs on Arch Linux is bad. How about change the default to GTK3 until the file dialog issue is fixed?

**Comment by yan12125** [comment]
Maybe we should have internal discussions first before proposing DE-specific changes to popular applications. I admit I've once done a similar thing - https://bugzilla.mozilla.org/show_bug.cgi?id=1432385, which is about CSD (Client Side Decoration) default in Firefox. Blame me if you find something strange in Firefox on LXQt!

**Comment by tsujan** [comment]
@yan12125 Most users know that Linux is flexible. An Arch/Manjaro/Debian/OpenSUSE user knows what he/she needs to do for customization. Ubuntu may pretend that its defaults are unchangeable things but that's not our problem.

That being said, it's good to make LXQt be recognized as a separate DE by developers of important programs like LibreOfiice and I really appreciate your efforts in this regard. In old times, there were only gnome and kde (although, ironically, Enlightenment came before them); now, whoever thinks that Linux is kde or gnome doesn't know Linux.

**Comment by tsujan** [comment]
BTW, although the pasting bug is fixed, now the default (non-native) Qt dialog is used instead of the LXQt file dialog. That can be seen as a regression.

**Comment by michaelweghorn** [comment]
> BTW, although the pasting bug is fixed, now the default (non-native) Qt dialog is used instead of the LXQt file dialog. That can be seen as a regression.

Please see https://bugs.documentfoundation.org/show_bug.cgi?id=122752 for the reasons. The native LXQt file dialog was missing custom LibreOffice controls, resulting in missing functionality which is why the non-native dialog is currently used. I don't know internals about the native LXQt dialog, but it MIGHT well be possible to implement that custom controls are shown there as well (by relying on its implementation details).

**Comment by tsujan** [comment]
@michaelweghorn Thanks again for your explanations!

It would be strange to me if LXQt file dialog lacked something from the default Qt file dialog. Actually, the former is much more advanced than the latter.

I'll read that report as soon as I find time. If there's something missing in LXQt file dialog, I could add it. Might need your help again.

**Comment by michaelweghorn** [comment]
> It would be strange to me if LXQt file dialog lacked something from the default Qt file dialog. Actually, the former is much more advanced than the latter.

@tsujan It's not that the LXQt file dialog itself is missing anything. The matter is that LibreOffice adds custom controls to the file dialog (e.g. a "Save with password" checkbox in the save dialog). And there doesn't seem to be a way to do this in a way that works independent of the actual dialog used (i.e. there is currently one implementation in LibreOffice to add them to the non-native Qt file dialog and one to do so for the KDE Plasma file dialog). The ideal solution would for sure be a way that doesn't rely on any implementation details and works for all dialogs (non-native and native ones), so if any has an idea how to do this, that would be welcome...

> I'll read that report as soon as I find time. If there's something missing in LXQt file dialog, I could add it. Might need your help again.

Please don't hesitate to ask. :-)
As far as I understand it currently: Unless there's a way to address the above problem (adding custom controls to QFileDialog) in a general, desktop-agnostic way, that handling would probably have to be implemented in LibreOffice.

**Comment by tsujan** [comment]
@michaelweghorn I understand your point; the default Qt file dialog is the safest dialog to add widgets to. Not using LXQt file dialog is not a big deal and I don't want to complicate the nice job that's done so far.

However, out of curiosity, I'll read that page :)

**Comment by tsujan** [comment]
OK, I read the report. I for one was convinced that, when checkboxes were to be added, the default Qt dialog should be used.

Maybe, instead of adding extra widgets to the file dialog, the relevant settings could be added to LibreOffice's general options but, in that case, they couldn't be changed by the user while he/she is saving something.

Other LXQt devs may have different opinions but, as I said above, I prefer not to complicate the current design. So, IMO, the default file dialog is OK -- at least, for now.

**Comment by michaelweghorn** [comment]
Thanks for the update.

> Maybe, instead of adding extra widgets to the file dialog, the relevant settings could be added to LibreOffice's general options but, in that case, they couldn't be changed by the user while he/she is saving something.

Right. In fact, what options are shown or not depends on the actual situation (e.g. whether a file is saved or an image is inserted in Writer or,...) and the user may want to set some options only for some files, etc., so having to set them in the general options doesn't seem to be a real alternative from a usability perspective. Another way might be to have a separate dialog in addition to the actual file dialog, but that isn't nice either.

**Comment by tsujan** [comment]
> Another way might be to have a separate dialog in addition to the actual file dialog, but that isn't nice either.

I agree.

**Comment by tsimonq2** [comment]
I was just pointed at this issue; apologies for missing it.

This was right around the 18.10 release when I worked to get this change in; this was in order to make LXQt use the Breeze theme instead of the GTK theme, because LibreOffice on Linux assumes that the DE is GTK. The context is [here](https://bugs.launchpad.net/ubuntu/+source/libreoffice/+bug/1799001). I'll admit I haven't followed this much after the release; thanks to @yan12125 for working with upstream on this, and I'll be happy to do anything I can at this point to help. I agree with the general point that from here on out we should discuss LXQt-specific functionality in popular applications prior to implementing things.

That being said, I would appreciate if some other developers could stop the "Ubuntu developers are stupid" insults, both in this issue and others, implied or directly stated. In Ubuntu we simply assume that the user doesn't want to have to customize everything all day long and wants some sane defaults; we're all working towards one common goal here, to make LXQt the best it can be, and just because our distributions are different doesn't give people the right to make cheap shots towards others. I don't appreciate it. Thanks for understanding.

**Comment by yan12125** [comment]
@tsimonq2 Thanks for following up! Do you think it's acceptable to go back to the `gtk3` plugin for LibreOffice in LXQt until there's way to make `kde5` and `gtk3_kde5` plugins work fine on both Ubuntu and Arch Linux? Specifically, in `libreoffice/vcl/source/app/salplug.cxx`, use `pStandardFallbackList` instead of `pKDEFallbackList` if `DESKTOP_LXQT` is detected.

**Comment by tsimonq2** [comment]
@yan12125 Sure, I think that's acceptable, but after switching back to `gtk3` we should make it a priority to figure out the problems with `kde5` and `gtk3_kde5`.

Please keep me in the loop (I'm also somewhat more responsive on IRC; tsimonq2 on freenode and OFTC).

**Comment by tsujan** [comment]
> That being said, I would appreciate if some other developers could stop the "Ubuntu developers are stupid" insults

Mind reading usually results in false conclusions like this. Instead, really reading what LXQt devs write could prevent such misunderstandings.

If Ubuntu wants to make LXQt better, that's very great. However, cherry-picking patches and giving them to Ubuntu users as LXQt has the opposite effect. That's why we say, "Please report Ubuntu problems to Ubuntu." It has nothing to do with "stupidity".

**Comment by yan12125** [comment]
> we should make it a priority to figure out the problems with kde5 and gtk3_kde5.

The problem is that, with `gtk3_kde5`, file dialogs requires `libKF5KIOFileWidgets.so.5` (`kio` package on Arch Linux) to work.

**Comment by agaida** [comment]
I see no big problems - as @tsujan mentioned the GTK theme works fine. All other things are strictly downstream problems firsthand. If we can help with something we will do so.  But again, downstream problems are to be solved downstream.

**Comment by tsujan** [comment]
@agaida Actually, the new Qt skin (which is the default one under LXQt) is better than the GTK skin -- thanks to KDE devs' hard work -- but @yan12125 says it depends on `kio`. I thought the `kio` problem was fixed. If it isn't, yes, LXQt users can use the gtk skin for now.

**Comment by tsujan** [comment]
I don't see a kio process here when I open the Qt file dialog of the latest LibreOffice. After all, they chose the default Qt file dialog for reasons discussed above.

**Comment by agaida** [comment]
Nice to know - to be honest, it will take some time until it is considered in Debians tasksel - if one want to use it without changes, it will be in buster+1 :P So much time to test and eventually improve.

**Comment by yan12125** [comment]
> I don't see a kio process here when I open the Qt file dialog of the latest LibreOffice.

@tsujan Are you using `SAL_USE_VCLPLUGIN=qt5`? The kio issue appears with `SAL_USE_VCLPLUGIN=gtk3_kde5` only.

**Comment by tsujan** [comment]
> Are you using SAL_USE_VCLPLUGIN=qt5? The kio issue appears with SAL_USE_VCLPLUGIN=gtk3_kde5 only.

I didn't touch that EV. `echo $SAL_USE_VCLPLUGIN` says `kde4` but I'm sure its Qt5 because I've adjusted Kvantum's Qt5 code for LibreOffcice and all changes are reflected by it.

I don't think Manjaro (my distro) has made any change to LibreOffice.

**Comment by tsujan** [comment]
This is definitely the Qt5 skin:

![writer-kvantum](https://user-images.githubusercontent.com/981076/55684636-b7fd2b00-5962-11e9-81f1-b356d76084a2.png)

LibreOffice was upgraded and the only thing I touched was Kvantum.

**Comment by yan12125** [comment]
Oh, I forgot you have kio installed. The issue only affects users without kio.

**Comment by tsujan** [comment]
> Oh, I forgot you have kio installed. The issue only affects users without kio.

But `kio` isn't used; it's neither a dependency. I'm confused...

**Comment by yan12125** [comment]
Well, IIUIC libreoffice loads `/usr/lib/libreoffice/program/libvclplug_kde5lo.so`, and the latter uses kio libraries.

**Comment by tsujan** [comment]
So, why don't I see any kio process?

**Comment by tsujan** [comment]
Anyway, if so, that's a LibreOffice issue that should be fixed by its devs. I don't think we need to add any workaround.

**Comment by yan12125** [comment]
The program `lo_kde5filepicker` (requires kio) is used when `SAL_USE_VCLPLUGIN=gtk3_kde5`, which is the default is kio is not installed.

> Anyway, if so, that's a LibreOffice issue that should be fixed by its devs. I don't think we need to add any workaround.

Can't agree more. I'm waiting for @tsimonq2's response for the issue before proposing changes to LibreOffice.

**Comment by tsimonq2** [comment]
@yan12125 I did reply above, do you have other questions you would like me to answer? :)

**Comment by yan12125** [comment]
Sorry, I misread your response. You did answer me :)

**Comment by yan12125** [comment]
As a side note, here's the new upstream ticket https://bugs.documentfoundation.org/show_bug.cgi?id=124598

**Comment by yan12125** [comment]
Thanks @agaida! As a side note, the upstream bug is fixed in master and the fix will be included in 6.2.4.
