### ISSUE TITLE
lxqt-panel: cut text in several plugins

### ISSUE THREAD

**Issue by pmattern** [lxqt/lxqt#632]
In several panel plugins text happens to get cut besides the available space doesn't enforce it.

This affects, at least among other, plugin-[world]clock and plugin-kbindicator
![lxqt_panel_plugins_text-cut](https://cloud.githubusercontent.com/assets/9860801/7473253/25c99e2c-f33a-11e4-9b72-2cf14099685f.png)
Note the correct display of font in the Task manager button at the left.

A similar problem could be seen in plugin Volume control but was affecting the plugin UI itself, not the panel icon, see #538.

So I thought I'd open this issue as kind of summary addressing this problem as a whole and regardless of some particular plugin. Maybe some kind of revision of all related components would make sense so as to prevent this problem from coming up again and again.

**Comment by palinek** [comment]
IMO
- `kbindicator` is/was caused by setting the size of panel and the margin/padding configured in theme
- `wordclock` is connected to font metrics and different widths of particular letters/numbers (similar as in #660)

**Comment by palinek** [comment]
@pmattern is this one still valid?

**Comment by pmattern** [comment]
@palinek 
I remember that I saw this once more a while ago but don't remember the details as this problem is rather long-standing and hence I didn't pay too much attention.
Issue is tagged 0.11 anyway. Maybe we can leave it open until 0.11 is about to be released and close if it cannot be reproduced any more till then?

**Comment by palinek** [comment]
OK

**Comment by pmattern** [comment]
In current lxde/lxqt-panel@9713796 the problem can still be seen when plugin-worldclock gets modified in a way that changes the space it needs.
E. g. when displaying seconds gets enabled in a running instance the text gets cut. Similarly, plugin-worldclock is reserving more space than needed when displaying seconds gets disabled, namely exactly the amount of space needed to display the seconds before. Strictly speaking this second finding is something different than addressed in this issue but pretty likely caused by the same underlying problem.
But both these problems cease when another session gets started and plugin-clock isn't affected at all. So just saying...

**Comment by palinek** [comment]
> In current lxde/lxqt-panel@9713796 the problem can still be seen when plugin-worldclock gets modified in a way that changes the space it needs

Sorry to disapoint you, but I will not dedicate my time to solve this. I've digged into this kind of problem multiple times in plugin-clock (maybe also in plugin-worldclock) and it was always very frustrating & time consuming (maybe I'm not smart enought for this kind of tasks). Now I'm lacking enthusiasm for this.

**Comment by pmattern** [comment]
Running latest VCS code on Arch Linux, all of a sudden...
![lxqt-panel_plugins-in-general_cropped-text-worldclock](https://cloud.githubusercontent.com/assets/9860801/15099910/d4451eee-1563-11e6-8115-fcff81663bcb.png)
Not aware of any tweaking or any change regarding LXQt as a whole which may have caused this. Only thing relevant *could* be that a rather large number of windows was running in `plugin-taskbar` on a regular basis recently using all of the horizontal space available. But now that the problem cropped up again it can be seen on virtual desktops where `plugin-taskbar` is completely empty, too.

Probably we should modify the milestone here.

**Comment by stefonarch** [comment]
Cannot reproduce this, even with 20 windows open.
Latest packages from Aur compiled just now.
![schermata05](https://cloud.githubusercontent.com/assets/10681413/15106906/9bb3d174-15cc-11e6-848d-f224ae8bf5b3.png)

**Comment by pmattern** [comment]
It's not happening all the time and you have the date displayed which may make a difference, too.

**Comment by stefonarch** [comment]
Just tested without date, still everything ok. So you should find what triggers that.

**Comment by tsimonq2** [comment]
I can still reproduce this and it is still an issue.

**Comment by agaida** [comment]
with the merger of clock and worldclock plugin we should fix this too

**Comment by tsimonq2** [comment]
I do remember it fixing itself once I restarted the panel (after adding worldclock) so I have a pretty good idea of where to start here. 

I can take this one. I'll work on it once my PR merging the clock and world clock plugins has landed in the lxqt-panel master branch.

**Comment by palinek** [comment]
fixed in  lxde/lxqt-panel#438

**Comment by tsujan** [comment]
Unfortunately, the cut text still happens in world clock -- I saw it in VirtualBox, when I moved some widgets. A panel restart fixes it though.

**Comment by wxl** [comment]
Can we get a clear set of steps to reproduce this? Like which widgets do you need to have arranged which way?

**Comment by tsujan** [comment]
@wxl I was wrong about moving widgets; reported it here: https://github.com/lxqt/lxqt-panel/issues/1056
