### ISSUE TITLE
lxqt-panel - Error image is NULL

### ISSUE THREAD

**Issue by ArthurBorsboom** [lxqt/lxqt#884]
In the systemd-journal I see the following error messages.

> Nov 07 14:50:14 pb450 lxqt-panel[1717]:     \* Error image is NULL
> Nov 07 14:50:14 pb450 lxqt-panel[1717]:     \* Error image is NULL
> Nov 07 14:50:14 pb450 lxqt-panel[1717]:     \* Error image is NULL

I believe it is related to the systray icon of the GTK3 application I use, called Xpad.
My guess is that Xpad does not provide the icon which lxqt-panel is looking for.

During the installation Xpad has provided an icon in the following location.
/usr/share/icons/hicolor/scalable/apps/xpad.svg

Is this an issue with lxqt-panel or should Xpad be changed in some way?
If so, do you have any suggestions?

**Comment by palinek** [comment]
Is there any icon (of the suspected Xpad) shown in the tray?

**Comment by ArthurBorsboom** [comment]
Yes, the Xpad icon does show. However it is very small. If I reload Xpad or
the lxqt-panel, often the icon does show correct on the right/expected size.

**Comment by palinek** [comment]
We are talking here about the `plugin-tray` which is implementing the old (deprecated?) [Xembed](http://standards.freedesktop.org/xembed-spec/xembed-spec-0.5.html).
lxqt-panel already got the support for the newer [status notifier](http://www.freedesktop.org/wiki/Specifications/StatusNotifierItem/) in `plugin-statusnotifier`. We're keeping the `plugin-tray` only for backward compatibility. The warning you are observing comes from this [code](https://github.com/lxde/lxqt-panel/blob/master/plugin-tray/trayicon.cpp#L304). I don't know much about the implementation....and I would rather not spend much time digging into it (as it is deprecated).

@paulolieuthier @jleclanche GTK3 app should be aware of the SNI, not? Are there any libraries/packages needed?

**Comment by paulolieuthier** [comment]
GTK3 apps still need the libappindicator libraries (which in Arch AFAIK don't work). With that, it should work. I'm having an issue with nm-applet's icon as well. nm-applet was recently ported to GTK3. I'll try to take a look at that.

As a side note, [xembed-sni-proxy](https://github.com/davidedmundson/xembed-sni-proxy) kind of stabilized.

**Comment by palinek** [comment]
> As a side note, xembed-sni-proxy kind of stabilized.
```
THIS REPO IS NOW CLOSED

Code is merged in plasma-workspace

All commits, bugs changes should go there as I won't check here, and merging it harder.

Thanks for all the testing!
```

**Comment by paulolieuthier** [comment]
@palinek yep, it was good enough to go to Plasma (which was the original purpose).

**Comment by paulolieuthier** [comment]
> Yes, the Xpad icon does show. However it is very small. If I reload Xpad or the lxqt-panel, often the icon does show correct on the right/expected size.

Exactly the same as nm-applet.

**Comment by palinek** [comment]
> @palinek yep, it was good enough to go to Plasma (which was the original purpose).

So... do you intend to take/fork it and use/incorporate into plugin-statusnotifier?

**Comment by paulolieuthier** [comment]
@palinek no, I think LXQt should maintain plugin-tray for as long as the foreseeable future. We can borrow their code as it's clean, working and xcb-only.

**Comment by ArthurBorsboom** [comment]
Gtk3 has deprecated the GtkStatusIcon in favor of notifications.

> [GtkStatusIcon](https://developer.gnome.org/gtk3/stable/GtkStatusIcon.html) has been deprecated in 3.14. You should consider using notifications or more modern platform-specific APIs instead. GLib provides the [GNotification](https://developer.gnome.org/gio/stable/GNotification.html) API which works well with GtkApplication. Also see this [HowDoI](https://developer.gnome.org/GNotification).

Since I am the maintainer of [Xpad](https://launchpad.net/xpad), I don't mind to migrate the systray functionality of Xpad to a better solution. Hopefully in a way that it works for LXQt, Unity and other common desktop environments. Since I am not too familiar with modern systrays, if you have any suggestions, I am all ears.

**Comment by ArthurBorsboom** [comment]
But in the mean time, it would be nice if the existing issue of the small icons combined with the Image is NULL error could be solved. :)

**Comment by ArthurBorsboom** [comment]
Is there anything I can do to help on this issue (without Qt knowledge)?

**Comment by paulolieuthier** [comment]
I played with it some time ago, and had no success. Will try again soon, I'll ping you then.

**Comment by paulolieuthier** [comment]
@ArthurBorsboom my problem with nm-applet was solved with recent commits. Could you try again?

**Comment by ArthurBorsboom** [comment]
Hi Paulo,

I have the latest lxqt-panel-git already installed and the problem still exists. However, I have a mix of repository version packages of lxqt v0.10 and git versions (mainly because of different lxqt-panel issues).

Which package do you mean when you referred to "recent commits"?

**Comment by paulolieuthier** [comment]
I meant lxqt-panel.

**Comment by ArthurBorsboom** [comment]
I believe I have the latest lxqt-panel running.
```
local/lxqt-panel-git 0.10.0.47.ga54062f-1
```
However, I am still getting the issue, instantly after booting in the journal.

```
Feb 03 19:21:00 z97 lxqt-panel[948]:     * Error image is NULL
Feb 03 19:21:00 z97 lxqt-panel[948]:     * Error image is NULL
Feb 03 19:20:59 z97 NetworkManager[829]: <info>  startup complete
Feb 03 19:20:59 z97 lxqt-panel[948]:     * Error image is NULL
Feb 03 19:20:59 z97 lxqt-panel[948]:     * Error image is NULL
Feb 03 19:20:59 z97 lxqt-panel[948]:     * Error image is NULL
Feb 03 19:20:57 z97 lxqt-panel[948]:     * Error image is NULL
```

Am I missing something, or might it be something else?

**Comment by paulolieuthier** [comment]
Well, I didn't check if the warning is being emmited here. I'm talking about the icon appearing correctly.

**Comment by ArthurBorsboom** [comment]
Ah okay. I have to keep an eye on it, since I recall it most of the time
not working and sometimes it did. Currently the icon is showing, but the
image looks a bit malformed on the sides / bottom.

**Comment by ArthurBorsboom** [comment]
For some reason it seems the most to the right GTK icon, is usually or maybe always malformed. The xpad icon has some random pixels around, as you can see in this screenshot.

![2016-02-03-223855_1920x32_scrot](https://cloud.githubusercontent.com/assets/6639859/12798004/5c5f19ca-cac7-11e5-92e8-954d4c086250.png)

**Comment by ArthurBorsboom** [comment]
To rephrase and summarize the still existing issue:

While using only the Lxqt git (Arch) packages, and when I start xpad, the error message appears exactly 5 times in the journal.
```
Apr 12 08:40:59 pb450 lxqt-panel[808]:     * Error image is NULL
Apr 12 08:40:59 pb450 lxqt-panel[808]:     * Error image is NULL
Apr 12 08:40:59 pb450 lxqt-panel[808]:     * Error image is NULL
Apr 12 08:40:59 pb450 lxqt-panel[808]:     * Error image is NULL
Apr 12 08:40:59 pb450 lxqt-panel[808]:     * Error image is NULL
```
Sometimes the GTK status icon gets shown correct, sometimes not.

![2016-04-12-084520_1680x33_scrot](https://cloud.githubusercontent.com/assets/6639859/14451923/150e44d4-008b-11e6-9423-677eb414ce06.png)

Any new thoughts on this?
